# File ini memberitahu Railway untuk menginstal semua paket sistem yang kita butuhkan.
[phases.setup]
# Menambahkan nodejs_20 (versi stabil Node.js) dan npm ke dalam daftar.
nixPkgs = ["nodejs_20", "npm_10", "python3", "yt-dlp", "ffmpeg"]

# Menentukan perintah untuk memulai aplikasi Anda.
[start]
cmd = "npm run start"
