# File ini hanya memberitahu Railway untuk menginstal paket sistem TAMBAHAN.
# Node.js dan npm akan diinstal secara otomatis karena ada file package.json.
[phases.setup]
nixPkgs = ["python3", "yt-dlp", "ffmpeg"]

# Menentukan perintah untuk memulai aplikasi Anda.
[start]
cmd = "npm run start"
